services:
  mariadb:
    container_name: inception-mariadb
    build: ./requirements/mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - inception-net
    volumes:
      - ~/inception_data/db_files:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: inception-wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ~/inception_data/wp_files:/var/www/inception
    networks:
      - inception-net
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    container_name: inception_nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ~/inception_data/wp_files:/var/www/inception
    networks:
      - inception-net
    env_file:
      - .env

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_fileses

networks:
  inception-net:
    driver: bridge
