services:
  mariadb:
    container_name: inception-mariadb
    build: ./requirements/mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - inception-net
    volumes:
      - ~/inception_data/db_files:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: inception-wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ~/inception_data/wp_files:/var/www/inception
    networks:
      - inception-net
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/nginx/
      args:
        SSL_PATH: ${SSL_PATH}
        SSL_CERT: ${SSL_CERT}
        SSL_KEY: ${SSL_KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    container_name: inception_nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ~/inception_data/wp_files:/var/www/inception
    networks:
      - inception-net
    env_file:
      - .env

networks:
  inception-net:
    driver: bridge
