services:
  mariadb:
    container_name: inception-mariadb
    build: ./requirements/mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - inception-net
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: inception-wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./requirements/wordpress:/var/www/html
    networks:
      - inception-net

  nginx:
    build: ./requirements/nginx
    container_name: inception_nginx
    restart: always
    ports:
      - "8443:443"
    depends_on:
      - wordpress
    volumes:
      - ./requirements/wordpress:/var/www/html
    networks:
      - inception-net

volumes:
  db_data:

networks:
  inception-net:
    driver: bridge
